# -*- coding: utf-8 -*-
"""VCNN_helin_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jtGhBVsF9VpBBUqQAdWMRpcQi9mk5iV0
"""

# -*- coding: utf-8 -*-
import numpy as np
import scipy
import math
import matplotlib.pyplot as plt
#from sympy import Symbol, nsolve, solve
#from sympy.solvers import solve
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
from matplotlib import animation as animation

from PIL import Image
import matplotlib as mpl
import time

from tensorflow.python.keras.layers import Input, Dense, Convolution2D, MaxPooling2D, UpSampling2D,Cropping2D, AveragePooling2D,Dense,Flatten,Reshape,Dropout
from tensorflow.python.keras.models import Model,Sequential
import tensorflow as tf

import tensorflow as tf

from tensorflow.python.keras.layers import LSTM,LeakyReLU,RepeatVector
from tensorflow.python.keras.callbacks import EarlyStopping
from tensorflow.python.keras.callbacks import ModelCheckpoint

from tensorflow import keras
import pickle
import keras
from keras.layers import LeakyReLU
from keras import backend as K
from keras import optimizers

from google.colab import drive
drive.mount('/content/drive')

datasize = 9261
repeat_sample = 2

test_index = list(range(1,datasize*repeat_sample,10))
train_index = list(set(range(1,datasize*repeat_sample)) - set(range(1,datasize*repeat_sample,10)))

vor_data = np.load('drive/MyDrive/VCNN_test/data/helin/vor_field_data_apower1_2.npy')
true_data = np.load('drive/MyDrive/VCNN_test/data/helin/true_field_data_apower1_2.npy')

vor_train = vor_data[train_index,:,:]
vor_test = vor_data[test_index,:,:]

del vor_data

true_train = true_data[train_index,:,:]
true_test = true_data[test_index,:,:]

del true_data

input_img = Input(shape=(171,171,1))
x = Convolution2D(48, (8,8),activation='relu', padding='same')(input_img)
x = Convolution2D(48, (8,8),activation='relu', padding='same')(x)
x = Convolution2D(48, (8,8),activation='relu', padding='same')(x)
x = Convolution2D(48, (8,8),activation='relu', padding='same')(x)
x = Convolution2D(48, (8,8),activation='relu', padding='same')(x)
x = Convolution2D(48, (8,8),activation='relu', padding='same')(x)
x = Convolution2D(48, (8,8),activation='relu', padding='same')(x)
x_final = Convolution2D(1, (8,8), padding='same')(x)
model = Model(input_img, x_final)
model.compile(optimizer='adam', loss='mse')


model.summary()


K.set_value(model.optimizer.learning_rate, 0.0001)
history = model.fit(vor_train, true_train,epochs=50,validation_split=0.05, batch_size=64,shuffle=True)

model.save('drive/MyDrive/VCNN_test/model/nuclear_VCNN_9261_fix_apower1_large.h5')

predict_test = model.predict(vor_test)

np.save('drive/MyDrive/VCNN_test/data/helin/test_results.npy',predict_test)

